default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 1
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: learning_development

test:
  <<: *default
  database: learning_test

production:
  <<: *default
  database: learning_production
